\copy aka_name        from '/path_to/imdb/aka_name.csv' csv escape '\'
\copy aka_title       from '/path_to/imdb/aka_title.csv' csv escape '\'
\copy cast_info       from '/path_to/imdb/cast_info.csv' csv escape '\'
\copy char_name       from '/path_to/imdb/char_name.csv' csv escape '\'
\copy comp_cast_type  from '/path_to/imdb/comp_cast_type.csv' csv escape '\'
\copy company_name    from '/path_to/imdb/company_name.csv' csv escape '\'
\copy company_type    from '/path_to/imdb/company_type.csv' csv escape '\'
\copy complete_cast   from '/path_to/imdb/complete_cast.csv' csv escape '\'
\copy info_type       from '/path_to/imdb/info_type.csv' csv escape '\'
\copy keyword         from '/path_to/imdb/keyword.csv' csv escape '\'
\copy kind_type       from '/path_to/imdb/kind_type.csv' csv escape '\'
\copy link_type       from '/path_to/imdb/link_type.csv' csv escape '\'
\copy movie_companies from '/path_to/imdb/movie_companies.csv' csv escape '\'
\copy movie_info      from '/path_to/imdb/movie_info.csv' csv escape '\'
\copy movie_info_idx  from '/path_to/imdb/movie_info_idx.csv' csv escape '\'
\copy movie_keyword   from '/path_to/imdb/movie_keyword.csv' csv escape '\'
\copy movie_link      from '/path_to/imdb/movie_link.csv' csv escape '\'
\copy name            from '/path_to/imdb/name.csv' csv escape '\'
\copy person_info     from '/path_to/imdb/person_info.csv' csv escape '\'
\copy role_type       from '/path_to/imdb/role_type.csv' csv escape '\'
\copy title           from '/path_to/imdb/title.csv' csv escape '\'


