\copy aka_name        from '/ocz/pg104/pg_plan_advsr/JOB/imdb/aka_name.csv' csv escape '\'
\copy aka_title       from '/ocz/pg104/pg_plan_advsr/JOB/imdb/aka_title.csv' csv escape '\'
\copy cast_info       from '/ocz/pg104/pg_plan_advsr/JOB/imdb/cast_info.csv' csv escape '\'
\copy char_name       from '/ocz/pg104/pg_plan_advsr/JOB/imdb/char_name.csv' csv escape '\'
\copy comp_cast_type  from '/ocz/pg104/pg_plan_advsr/JOB/imdb/comp_cast_type.csv' csv escape '\'
\copy company_name    from '/ocz/pg104/pg_plan_advsr/JOB/imdb/company_name.csv' csv escape '\'
\copy company_type    from '/ocz/pg104/pg_plan_advsr/JOB/imdb/company_type.csv' csv escape '\'
\copy complete_cast   from '/ocz/pg104/pg_plan_advsr/JOB/imdb/complete_cast.csv' csv escape '\'
\copy info_type       from '/ocz/pg104/pg_plan_advsr/JOB/imdb/info_type.csv' csv escape '\'
\copy keyword         from '/ocz/pg104/pg_plan_advsr/JOB/imdb/keyword.csv' csv escape '\'
\copy kind_type       from '/ocz/pg104/pg_plan_advsr/JOB/imdb/kind_type.csv' csv escape '\'
\copy link_type       from '/ocz/pg104/pg_plan_advsr/JOB/imdb/link_type.csv' csv escape '\'
\copy movie_companies from '/ocz/pg104/pg_plan_advsr/JOB/imdb/movie_companies.csv' csv escape '\'
\copy movie_info      from '/ocz/pg104/pg_plan_advsr/JOB/imdb/movie_info.csv' csv escape '\'
\copy movie_info_idx  from '/ocz/pg104/pg_plan_advsr/JOB/imdb/movie_info_idx.csv' csv escape '\'
\copy movie_keyword   from '/ocz/pg104/pg_plan_advsr/JOB/imdb/movie_keyword.csv' csv escape '\'
\copy movie_link      from '/ocz/pg104/pg_plan_advsr/JOB/imdb/movie_link.csv' csv escape '\'
\copy name            from '/ocz/pg104/pg_plan_advsr/JOB/imdb/name.csv' csv escape '\'
\copy person_info     from '/ocz/pg104/pg_plan_advsr/JOB/imdb/person_info.csv' csv escape '\'
\copy role_type       from '/ocz/pg104/pg_plan_advsr/JOB/imdb/role_type.csv' csv escape '\'
\copy title           from '/ocz/pg104/pg_plan_advsr/JOB/imdb/title.csv' csv escape '\'


